'''         -*- coding: utf-8 -*-
Form implementation generated from reading ui file 'Error_dialog.ui'
Created by: PyQt5 UI code generator 5.15.0
WARNING: Any manual changes made to this file will be lost when pyuic5 is run again.
Do not edit this file unless you know what you are doing.'''




#                   FINAL PROJECT ON FANTASY CRICKET LEAGUE 
#                               By VUNNAM ANAND
 

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_errorDialog(object):
    def setupUi(self, errorDialog):
        errorDialog.setObjectName("errorDialog")
        errorDialog.resize(450, 180)
        errorDialog.setMinimumSize(QtCore.QSize(500, 180))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        errorDialog.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        errorDialog.setFont(font)
        errorDialog.setStyleSheet("background-color:rgb(204,204,204);")
        self.gridLayout = QtWidgets.QGridLayout(errorDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.errormsglabel = QtWidgets.QLabel(errorDialog)
        self.errormsglabel.setObjectName("errormsglabel")
        self.gridLayout.addWidget(self.errormsglabel, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okbtn = QtWidgets.QPushButton(errorDialog)
        self.okbtn.setObjectName("okbtn")
        self.horizontalLayout.addWidget(self.okbtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.errormsglabel.setWordWrap(True)
        self.label = QtWidgets.QLabel(errorDialog)
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("close.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 2)
        self.okbtn.clicked.connect(lambda :errorDialog.close()) # Close the dialog when ok button is clicked
        self.okbtn.setStyleSheet("border:1px solid black;\n"
        "padding:2px 25px 2px 25px; ")
        self.retranslateUi(errorDialog)
        QtCore.QMetaObject.connectSlotsByName(errorDialog)

    def retranslateUi(self, errorDialog):
        _translate = QtCore.QCoreApplication.translate
        errorDialog.setWindowTitle(_translate("errorDialog", "Error"))
        self.errormsglabel.setText(_translate("errorDialog", "Error message"))
        self.okbtn.setText(_translate("errorDialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    errorDialog = QtWidgets.QDialog()
    ui = Ui_errorDialog()
    ui.setupUi(errorDialog)
    errorDialog.show()
    sys.exit(app.exec_())
